### ISSUE TITLE
How traAdaBoost weights encoded in the model

### ISSUE THREAD

**Issue by HWZX** [beihaifusang/NER_Transfer_Learning-LSTM_with_Rule_Model#1]
汤神，想问你个问题，你用tradaboost迁移的时候不是要调整样本的权重吗，样本的权重是怎么在序列标注模型里体现的呢，我想基于crf做迁移，但是没搞明白权重值是怎么体现在模型里的

**Comment by beihaifusang** [comment]
昂，下次求把问题写在描述里面23333

**Comment by HWZX** [comment]
hhh好，头一次用issues

那就是说每个句子和对应的标注作为一个样例，对应一个weight是吧
然后我就想问你这个每个样例的weight是怎么体现在你LSTM的模型里的呢，我想用CRF作标注但是训练过程中并没有地方要用到样本的权重啊，就不太明白TrAdaboost算法是怎么把权重和基学习器结合起来的
